name = "MultiAgentPathFindingMILP"
uuid = "650eebd1-6f14-4290-b37f-a6e1320722b1"
authors = ["adfeel220 <adfeel220@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
